### ISSUE TITLE
Bug - Username incorrect for repository owned by Organization

### ISSUE THREAD

**Issue by nitrag** [aheze/SupportDocs#14]
Currently GITHUB_ACTOR is who pushed the code. I have this (awesome) repository in a Github Organization. The script needs to be updated as follows:

`GITHUB_USERNAME = FULL_GITHUB_REPOSITORY.split("/")[0]`

**Comment by hkamran80** [comment]
@nitrag I created SupportDocs repositories in one of my organizations, one with my patched code ([theOHgroup/test-supportdocs](https://github.com/theOHgroup/test-supportdocs/tree/DataSource)), and the other with the current code ([theOHgroup/test-supportdocs-upstream](https://github.com/theOHgroup/test-supportdocs-upstream/tree/DataSource)). Both are working as expected. Is there something you did differently than I?

**Comment by nitrag** [comment]
@hkamran80 The Github Action will run fine. As-is the `ACTOR` is the user who pushes the code so the urls in the documentation will be incorrect.

**Comment by hkamran80** [comment]
@nitrag Does the new code work? It was merged three days ago.

**Comment by nitrag** [comment]
Yes, thank you.
